/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as ClientSignupRouteImport } from './routes/client/signup'
import { Route as ClientLoginRouteImport } from './routes/client/login'
import { Route as ClientDashboardRouteImport } from './routes/client/dashboard'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api/sitemap[.]xml'
import { Route as ApiPurchaseCheckoutRouteImport } from './routes/api/purchase-checkout'
import { Route as ClientDashboardIndexRouteImport } from './routes/client/dashboard.index'
import { Route as ClientDashboardTicketsRouteImport } from './routes/client/dashboard.tickets'
import { Route as ClientDashboardSettingsRouteImport } from './routes/client/dashboard.settings'
import { Route as ClientDashboardReportsRouteImport } from './routes/client/dashboard.reports'
import { Route as ClientDashboardProjectsRouteImport } from './routes/client/dashboard.projects'
import { Route as ClientDashboardPackagesRouteImport } from './routes/client/dashboard.packages'
import { Route as ClientDashboardNotificationsRouteImport } from './routes/client/dashboard.notifications'
import { Route as ClientDashboardBillingRouteImport } from './routes/client/dashboard.billing'
import { Route as ApiPublicBlogRouteImport } from './routes/api/public/blog'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/team.lazy').then((d) => d.Route))
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/pricing.lazy').then((d) => d.Route))
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/blog.lazy').then((d) => d.Route))
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const ClientSignupRoute = ClientSignupRouteImport.update({
  id: '/client/signup',
  path: '/client/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/client/login',
  path: '/client/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/client/dashboard',
  path: '/client/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPurchaseCheckoutRoute = ApiPurchaseCheckoutRouteImport.update({
  id: '/api/purchase-checkout',
  path: '/api/purchase-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardIndexRoute = ClientDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardTicketsRoute = ClientDashboardTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardSettingsRoute = ClientDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardReportsRoute = ClientDashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardProjectsRoute = ClientDashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardPackagesRoute = ClientDashboardPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardNotificationsRoute =
  ClientDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ClientDashboardRoute,
  } as any)
const ClientDashboardBillingRoute = ClientDashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ApiPublicBlogRoute = ApiPublicBlogRouteImport.update({
  id: '/api/public/blog',
  path: '/api/public/blog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/api/purchase-checkout': typeof ApiPurchaseCheckoutRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/client/dashboard': typeof ClientDashboardRouteWithChildren
  '/client/login': typeof ClientLoginRoute
  '/client/signup': typeof ClientSignupRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/api/public/blog': typeof ApiPublicBlogRoute
  '/client/dashboard/billing': typeof ClientDashboardBillingRoute
  '/client/dashboard/notifications': typeof ClientDashboardNotificationsRoute
  '/client/dashboard/packages': typeof ClientDashboardPackagesRoute
  '/client/dashboard/projects': typeof ClientDashboardProjectsRoute
  '/client/dashboard/reports': typeof ClientDashboardReportsRoute
  '/client/dashboard/settings': typeof ClientDashboardSettingsRoute
  '/client/dashboard/tickets': typeof ClientDashboardTicketsRoute
  '/client/dashboard/': typeof ClientDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/api/purchase-checkout': typeof ApiPurchaseCheckoutRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/client/login': typeof ClientLoginRoute
  '/client/signup': typeof ClientSignupRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/api/public/blog': typeof ApiPublicBlogRoute
  '/client/dashboard/billing': typeof ClientDashboardBillingRoute
  '/client/dashboard/notifications': typeof ClientDashboardNotificationsRoute
  '/client/dashboard/packages': typeof ClientDashboardPackagesRoute
  '/client/dashboard/projects': typeof ClientDashboardProjectsRoute
  '/client/dashboard/reports': typeof ClientDashboardReportsRoute
  '/client/dashboard/settings': typeof ClientDashboardSettingsRoute
  '/client/dashboard/tickets': typeof ClientDashboardTicketsRoute
  '/client/dashboard': typeof ClientDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/api/purchase-checkout': typeof ApiPurchaseCheckoutRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/client/dashboard': typeof ClientDashboardRouteWithChildren
  '/client/login': typeof ClientLoginRoute
  '/client/signup': typeof ClientSignupRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/api/public/blog': typeof ApiPublicBlogRoute
  '/client/dashboard/billing': typeof ClientDashboardBillingRoute
  '/client/dashboard/notifications': typeof ClientDashboardNotificationsRoute
  '/client/dashboard/packages': typeof ClientDashboardPackagesRoute
  '/client/dashboard/projects': typeof ClientDashboardProjectsRoute
  '/client/dashboard/reports': typeof ClientDashboardReportsRoute
  '/client/dashboard/settings': typeof ClientDashboardSettingsRoute
  '/client/dashboard/tickets': typeof ClientDashboardTicketsRoute
  '/client/dashboard/': typeof ClientDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/team'
    | '/terms'
    | '/api/purchase-checkout'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/client/dashboard'
    | '/client/login'
    | '/client/signup'
    | '/portfolio/$slug'
    | '/api/public/blog'
    | '/client/dashboard/billing'
    | '/client/dashboard/notifications'
    | '/client/dashboard/packages'
    | '/client/dashboard/projects'
    | '/client/dashboard/reports'
    | '/client/dashboard/settings'
    | '/client/dashboard/tickets'
    | '/client/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/team'
    | '/terms'
    | '/api/purchase-checkout'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/client/login'
    | '/client/signup'
    | '/portfolio/$slug'
    | '/api/public/blog'
    | '/client/dashboard/billing'
    | '/client/dashboard/notifications'
    | '/client/dashboard/packages'
    | '/client/dashboard/projects'
    | '/client/dashboard/reports'
    | '/client/dashboard/settings'
    | '/client/dashboard/tickets'
    | '/client/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/team'
    | '/terms'
    | '/api/purchase-checkout'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/client/dashboard'
    | '/client/login'
    | '/client/signup'
    | '/portfolio/$slug'
    | '/api/public/blog'
    | '/client/dashboard/billing'
    | '/client/dashboard/notifications'
    | '/client/dashboard/packages'
    | '/client/dashboard/projects'
    | '/client/dashboard/reports'
    | '/client/dashboard/settings'
    | '/client/dashboard/tickets'
    | '/client/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  ApiPurchaseCheckoutRoute: typeof ApiPurchaseCheckoutRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  ClientDashboardRoute: typeof ClientDashboardRouteWithChildren
  ClientLoginRoute: typeof ClientLoginRoute
  ClientSignupRoute: typeof ClientSignupRoute
  ApiPublicBlogRoute: typeof ApiPublicBlogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/client/signup': {
      id: '/client/signup'
      path: '/client/signup'
      fullPath: '/client/signup'
      preLoaderRoute: typeof ClientSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/login': {
      id: '/client/login'
      path: '/client/login'
      fullPath: '/client/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/client/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/purchase-checkout': {
      id: '/api/purchase-checkout'
      path: '/api/purchase-checkout'
      fullPath: '/api/purchase-checkout'
      preLoaderRoute: typeof ApiPurchaseCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/dashboard/': {
      id: '/client/dashboard/'
      path: '/'
      fullPath: '/client/dashboard/'
      preLoaderRoute: typeof ClientDashboardIndexRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/client/dashboard/tickets': {
      id: '/client/dashboard/tickets'
      path: '/tickets'
      fullPath: '/client/dashboard/tickets'
      preLoaderRoute: typeof ClientDashboardTicketsRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/client/dashboard/settings': {
      id: '/client/dashboard/settings'
      path: '/settings'
      fullPath: '/client/dashboard/settings'
      preLoaderRoute: typeof ClientDashboardSettingsRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/client/dashboard/reports': {
      id: '/client/dashboard/reports'
      path: '/reports'
      fullPath: '/client/dashboard/reports'
      preLoaderRoute: typeof ClientDashboardReportsRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/client/dashboard/projects': {
      id: '/client/dashboard/projects'
      path: '/projects'
      fullPath: '/client/dashboard/projects'
      preLoaderRoute: typeof ClientDashboardProjectsRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/client/dashboard/packages': {
      id: '/client/dashboard/packages'
      path: '/packages'
      fullPath: '/client/dashboard/packages'
      preLoaderRoute: typeof ClientDashboardPackagesRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/client/dashboard/notifications': {
      id: '/client/dashboard/notifications'
      path: '/notifications'
      fullPath: '/client/dashboard/notifications'
      preLoaderRoute: typeof ClientDashboardNotificationsRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/client/dashboard/billing': {
      id: '/client/dashboard/billing'
      path: '/billing'
      fullPath: '/client/dashboard/billing'
      preLoaderRoute: typeof ClientDashboardBillingRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/api/public/blog': {
      id: '/api/public/blog'
      path: '/api/public/blog'
      fullPath: '/api/public/blog'
      preLoaderRoute: typeof ApiPublicBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface ClientDashboardRouteChildren {
  ClientDashboardBillingRoute: typeof ClientDashboardBillingRoute
  ClientDashboardNotificationsRoute: typeof ClientDashboardNotificationsRoute
  ClientDashboardPackagesRoute: typeof ClientDashboardPackagesRoute
  ClientDashboardProjectsRoute: typeof ClientDashboardProjectsRoute
  ClientDashboardReportsRoute: typeof ClientDashboardReportsRoute
  ClientDashboardSettingsRoute: typeof ClientDashboardSettingsRoute
  ClientDashboardTicketsRoute: typeof ClientDashboardTicketsRoute
  ClientDashboardIndexRoute: typeof ClientDashboardIndexRoute
}

const ClientDashboardRouteChildren: ClientDashboardRouteChildren = {
  ClientDashboardBillingRoute: ClientDashboardBillingRoute,
  ClientDashboardNotificationsRoute: ClientDashboardNotificationsRoute,
  ClientDashboardPackagesRoute: ClientDashboardPackagesRoute,
  ClientDashboardProjectsRoute: ClientDashboardProjectsRoute,
  ClientDashboardReportsRoute: ClientDashboardReportsRoute,
  ClientDashboardSettingsRoute: ClientDashboardSettingsRoute,
  ClientDashboardTicketsRoute: ClientDashboardTicketsRoute,
  ClientDashboardIndexRoute: ClientDashboardIndexRoute,
}

const ClientDashboardRouteWithChildren = ClientDashboardRoute._addFileChildren(
  ClientDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  ApiPurchaseCheckoutRoute: ApiPurchaseCheckoutRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  ClientDashboardRoute: ClientDashboardRouteWithChildren,
  ClientLoginRoute: ClientLoginRoute,
  ClientSignupRoute: ClientSignupRoute,
  ApiPublicBlogRoute: ApiPublicBlogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
